apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: dasunsandeepa/platformservice:latest
          ports:
            - containerPort: 80
            - containerPort: 5000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: platforms-clusterip-srv
# spec:
#   type: ClusterIP
#   selector:
#     app: platformservice
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 80
#     - name: grpc
#       protocol: TCP
#       port: 5000
#       targetPort: 5000
