apiVersion: v1
kind: Service
metadata:
  name: platformnpservice-srv
spec:
  type: NodePort
  selector:
    app: platformservice # Selects your Pods with this label
  ports:
    - name: platformservice
      protocol: TCP
      port: 80 # Service port (inside cluster)
      targetPort: 80 # Container port
